### PR TITLE
Friday stuff

### PR DESCRIPTION
**Pull request by ethanbennett**
Merged stuff

### CODE REVIEW

**Comment by ethanbennett** [comment]
@Sh1pley  Averages methods work, they're all in merchant_repo for now. I still need to 1. move them around, 2. make them compliant with the spec harness, and 3. add tests, but they may help you with the standard deviation stuff

**Comment by ethanbennett** [comment]
@Sh1pley Average methods are now in Sales Analyst, and I got the spec harness more or less cooperating. There are five failures because I'm not rounding the numbers properly, but I'm too burnt out to make sense of the BigDecimal docs tonight, so I'll fix them in the morning. The one other failure is because I misunderstood the merchants_with_most_items spec--apparently they only need one that works with standard deviations, so we can get that working pretty easily tomorrow too.

**Comment by ethanbennett** [comment]
@Sh1pley with the exception of the two standard deviation methods that still remain for SalesAnalyst, iteration 1 is complete, fully tested, and fits the spec harness. Our merchant, sales_engine, and sales_analyst tests are between 76-84% covered, the rest are 100%.

**Comment by Sh1pley** [comment]
@ethanbennett nice man! Ill add the standard deviation shit right meow!

**Pull request merged**
